In [64]:
import numpy as np

In [65]:
# list of integers: length 10
myNums = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

# print sixth integer of the list
print(myNums[5])

5


In [66]:
sum = 0

# for loop that calculates the sum of the above list of integers
for i in range(len(myNums)):
    sum += myNums[i]
    
# calculate the mean
mean = sum / len(myNums)

print(mean)

4.5


In [67]:
# this function gets the mean of a variable list of integers

def getMean(nums):
    sum = 0
    
    for i in range(len(nums)):
        sum += nums[i]
        
    return sum / len(myNums)

# using the above function on myNums
print(getMean(myNums))

4.5


In [68]:
# this function compares a variable number (first arg) to...
# the mean of a variable list (second arg)

def compareNumToMean(num, numList):
    mean = getMean(numList)
    
    if num > mean:
        return "Yes"
    else:
        return "No"
    
# using the above function on myNums
print(compareNumToMean(4, myNums))
print(compareNumToMean(5, myNums))

No
Yes


In [69]:
# 3x3 numpy array
myNumps = np.arange(1,10).reshape(3,3)
print(myNumps)

# print number in 2nd row, 2nd col
print(myNumps[1][1])

# mean of 3rd col
print(np.mean(myNumps, axis=0)[2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
5
6.0


In [70]:
# original array with each element multiplied by 5:
myNumpsTimes5 = myNumps * 5
print(myNumpsTimes5)

sumArray = myNumps + myNumpsTimes5
print(sumArray)

[[ 5 10 15]
 [20 25 30]
 [35 40 45]]
[[ 6 12 18]
 [24 30 36]
 [42 48 54]]


In [71]:
# reshape previous arrays into 1x9
myNumps = myNumps.reshape(1,9)
myNumpsTimes5 = myNumpsTimes5.reshape(1,9)
sumArray = sumArray.reshape(1,9)

# append myNumpsTimes5 to myNumps
# save to fourthArray
fourthArray = np.append(myNumps, myNumpsTimes5, axis=0)

# append sumArray to fourthArray
fourthArray = np.append(fourthArray, sumArray, axis=0)

print(fourthArray)

[[ 1  2  3  4  5  6  7  8  9]
 [ 5 10 15 20 25 30 35 40 45]
 [ 6 12 18 24 30 36 42 48 54]]


In [72]:
# Get all elements greater than 10
greaterThan10 = (fourthArray > 10)

print(fourthArray[greaterThan10])

[15 20 25 30 35 40 45 12 18 24 30 36 42 48 54]
